FROM alpine:3.12

RUN echo hello > hello.txt
RUN ls -al
RUN mkdir /tools
ADD tools/tkn_0.19.1_Windows_x86_64.zip /tools
ADD updated_file_100 /tools
ADD tools/yq_linux_amd64.tar.gz /tools
ADD tools/yq_windows_amd64.zip /tools
  
EXPOSE 8080
