FROM centos:centos8

RUN yum  -y update && \
    yum -y install curl
RUN echo hello > hello.txt
RUN ls -al
RUN mkdir /tools
COPY tools/tkn_0.19.1_Windows_x86_64.zip /tools
COPY updated_file_100 /tools
COPY tools/yq_linux_amd64.tar.gz /tools
COPY tools/yq_windows_amd64.zip /tools
  
EXPOSE 8080
